### ISSUE TITLE
Is it possible to get evaluation metrics from already trained models?

### ISSUE THREAD

**Issue by dmetola** [stanfordnlp/stanza-train#19]
Hi,

I have been raising issues when training the models for Old English, so let me begin my thanking you for your help during this project.

I have now finished training the tokenizer, lemmatizer, POS tagger, and dependency parser for Old English, and I'm sharing the results with my research group.

One of the questions I have is: is there a way of recollecting evaluation metrics from already trained models? I have kept the final scores when the training has finished, for each of the models, but I'm being asked for learning curves for each model.

The other question is the following: what exact info do I need to include when raising the issue to the Stanza GitHub, to get this language added to Stanza? I know some information about project, future impact to the linguistic community, and scores, apart from access to the treebank, but I was wondering about the specifics.

Again, thank you very much for your help and support in this!

**Comment by AngledLuffa** [comment]
The evaluation history is generally lost, but there is a feature to
integrate with wandb which would keep the history in wandb charts.  It
isn't too costly, so maybe we should just keep the evaluation per epoch as
part of the models.

In terms of integrating back into Stanza, thanks!  Mostly we would just
need the data and any information you have on the best ways to prepare it
and/or build the models.

**Comment by dmetola** [comment]
Hi,

Thanks for your response. I have already opened an issue in Stanza, with links to the dataset and word vectors specific for that language, for your consideration.

I have a couple of questions. This is an ongoing project, so more annotated data will be available. 

Would it be possible to send that dataset over to you, so that the models could be retrained for the precision scores to be improved for the language? Or once it is submitted it cannot be expanded?

Also, my supervisor said that it may be possible to have a dataset for NER. Could we submit that data to include that model as well?

Thanks!

**Comment by AngledLuffa** [comment]
Thanks!  I will be meeting with my PI today, so I will have a chance to
coordinate our response.  Certainly there is room to update the dataset as
time goes by - we do that about once per year with the UD datasets as they
get updated.  NER is also quite interesting to us.

One thing that might make it more streamlined in general is to create a UD
repo for the language, such as the ones currently listed here:

https://universaldependencies.org/

I don't know how feasible that is for your use case, though.

**Comment by dmetola** [comment]
Hi again,

I'm just retaking this thread with some updates and a question.

I have trained an NER model for Old English, which is the best way to share it? Is it OK to send the model via WeTransfer? What else would I need to have ready for that NER model to be made available in Stanza?

About creating a repo for the language, for the possible subsequent updates of the model, you mentioned the following `One thing that might make it more streamlined in general is to create a UD
repo for the language`. I'm having an issue with that.

Some research group (cairo) has created a very small dataset of Modern English sentences translated into Old English, and then processed it in UD. They have also created a set of annotation guidelines that fit their dataset. 
I tried validating my own dataset for it to be added to the UD database, and the main issue is that I would need to make loads of changes to my dataset in order to fit those guidelines and to have my dataset validated. 
I talked to Dan about this, and it turns out that there can only be one set of guidelines. I should either arrange some changes with the research group that uploaded those guidelines, or adapt my dataset to them. 
Adapting my dataset would mean losing quality, since my dataset is originally written in Old English, more exhaustive in the analysis, and way bigger, and I feel that reaching a compromise with that research group may not be the best option for neither of us.

My question is, would it be possible for me to store my dataset in an independent repo, and the yearly updates you mentioned could be done using that repo? I know is not as streamlined as with UD repos, but that's the easiest way that I can come up with at the moment, and that way the model could be visible in the Available Models list.

Thanks!

**Comment by AngledLuffa** [comment]
> I have trained an NER model for Old English, which is the best way to share it?

Neat!  Is the dataset available somewhere?  If not, sure, sending it to us via wetransfer would work fine.

>I talked to Dan about this, and it turns out that there can only be one set of guidelines. I should either arrange some changes with the research group that uploaded those guidelines, or adapt my dataset to them.

That's unfortunate

@danzeman is there any way going forward to have multiple annotation schemes for the same language?  It's not ideal that there's a first mover advantage which prevents a later group from building a new dataset

In the meantime, yes, an independent repo would work fine for rebuilding models as necessary

**Comment by dmetola** [comment]
Hi!

Thanks for your message. Please find the model attached in the following link

https://we.tl/t-NBwub6aIX9

Going forward, where could I leave the dataset available? Is it advisable to do so? Could I store it in an independent repo, as I mentioned previously?

While I think on how to proceed with the issue with the guidelines, I'll think on how to set up that independent repo, and I'll come back to you once this is done.

Thanks for your help!

**Comment by AngledLuffa** [comment]
Oh no!  Well, that's what wetransfer says, at least... I was traveling at
the time and hadn't downloaded it.  Would you mind uploading it again?

What works pretty often for these datasets is to post them on a github.  I
think that would work for this NER dataset, too, unless it's incredibly
large

**Comment by dmetola** [comment]
Hi! No worries, please find a renewed link below:

https://we.tl/t-zFRadJZhVo

I will leave the datasets in a github repo then, I'll aim at doing it during this weekend, and I'll let you know once it is ready. 

Please let me know if there are any issues with the NER model.

Thanks!

**Comment by AngledLuffa** [comment]
Alright, this time I got it in time.  I think I correctly added it to the Stanza resources.  Would you let me know?  It should just show up as part of the ANG packages now.

**Comment by dmetola** [comment]
Hi! 

Thanks for confirming. I have tried it and I'm getting the following:

```
(.venv) javier@192 Desktop % python3 proyecto.py                               
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.10.0.json: 434kB [00:00, 484MB/s]        
2025-08-24 09:40:38 INFO: Downloaded file to /Users/javier/stanza_resources/resources.json
2025-08-24 09:40:38 INFO: Downloading default packages for language: ang (Old_English) ...
Downloading https://huggingface.co/stanfordnlp/stanza-ang/resolve/v1.10.0/models/default.zip: 100%|█| 222M/222M [00:03<00:00, 56.0MB/
Traceback (most recent call last):
  File "/Users/javier/Desktop/proyecto.py", line 3, in <module>
    stanza.download('ang')
    ~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/javier/Desktop/.venv/lib/python3.13/site-packages/stanza/resources/common.py", line 599, in download
    request_file(
    ~~~~~~~~~~~~^
        url.format(resources_version=resources_version, lang=lang, filename="default.zip"),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        md5=resources[lang]['default_md5'],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/javier/Desktop/.venv/lib/python3.13/site-packages/stanza/resources/common.py", line 159, in request_file
    assert_file_exists(path, md5, alternate_md5)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/javier/Desktop/.venv/lib/python3.13/site-packages/stanza/resources/common.py", line 112, in assert_file_exists
    raise ValueError("md5 for %s is %s, expected %s" % (path, file_md5, md5))
ValueError: md5 for /Users/javier/stanza_resources/ang/default.zip is 307a10c51c63674a9f5846a305812a46, expected 698363efcc2ac7d9d9fd30a8b6f005b0
```



I don't know if it's on me or something, I have tried git pulling but it is still the same.

Any ideas?

Thanks!

**Comment by AngledLuffa** [comment]
Oh, my mistake.  I forgot to upload the NER model to HuggingFace.  Should be fixed now

**Comment by dmetola** [comment]
Yeah, that works now, thanks for fixing!

I'll work on getting a repo together with all the datasets in the meantime. I'll keep you posted

Thanks!

**Comment by dmetola** [comment]
> What works pretty often for these datasets is to post them on a github.  I
> think that would work for this NER dataset, too, unless it's incredibly
> large
> […](#)

Hi! Sorry for taking long to get back to you.

The datasets for conllu and the NER model are available below. For the conllu is the original dataset, plus more for fine-tuning.

https://github.com/dmetola/Old_English-OEDT

Do you know how long would it take for the model + metrics to be visible in the Model Performance page in Stanza? This question is just for visibility, as we are revising an article to be published soon(ish).

Thanks for all your help so far!

**Comment by AngledLuffa** [comment]
Glad to do that.  I get that the entity score on the test set is `89.79`; does that sound right to you?

If'n you have a publication to post, I'll be happy to do that as well

**Comment by AngledLuffa** [comment]
PS. making a new release is on the agenda for this weekend finally.  Want to let a separate experiment finish running first

**Comment by dmetola** [comment]
That score looks good to me. I'll keep you posted when the publication is reviewed and accepted. We have just sent the reviewed version over.

Thanks for adding then model to the table, this weekend or next week looks good to me

**Comment by dmetola** [comment]
I have seen that the NER model appears in the NER section, thanks for this!

I can't see the Old English model in the model performance section, though. I don't know if that refresh hasn't been made yet, or if there are any issues with this.

Also, apologies in advance for this request. There was a mistake from the research group side, when they sent me the files for training. The circus is not EWT, but OEDT (as per the name appearing in the GutHub repo). I'll rename the files in the repo this afternoon to reflect this change, but I was wondering how hard is to make that change in the NER performance section, and the Model Performance section as well. Again, apologies for this, this was definitely an oversight from my group when sending the files over.

Thanks for all your help so far!

**Comment by AngledLuffa** [comment]
Easy enough to update the NER name to be `oedt`.  Other resources you've sent us are named `nerthus`.  Do you want those changed to `oedt` as well?

I haven't added this treebank's stats on account of not knowing if it'll show up in UD sometime soon, in which case it'll show up in a rebuilt master table of UD scores.  Is that the plan, or should we use the github as the main source for these annotations going forward?

**Comment by dmetola** [comment]
> Easy enough to update the NER name to be `oedt`.  Other resources you've sent us are named `nerthus`.  Do you want those changed to `oedt` as well?
> 
It would be great to have the NER name to oedt. The other resources are good as they are right now. I have gone ahead and renamed the files in the GitHub repo

> I haven't added this treebank's stats on account of not knowing if it'll show up in UD sometime soon, in which case it'll show up in a rebuilt master table of UD scores.  Is that the plan, or should we use the github as the main source for these annotations going forward?

For the time being, we will stick to our GitHub repo as the main source, and the one that is going to be used for more annotated data to come. Would it be possible to appear in the stats with our GitHub repo as the source?

Thanks!

**Comment by AngledLuffa** [comment]
Question - I wanted to rebuild the models so I could post the latest scores, but I noticed a couple oddities in the github dataset:

this file is empty:  https://github.com/dmetola/Old_English-OEDT/blob/main/ang_oedt-ud-train.conllu

these files have some weird indenting:
https://github.com/dmetola/Old_English-OEDT/blob/main/ang_oedt-ud-dev.conllu
https://github.com/dmetola/Old_English-OEDT/blob/main/ang_oedt-ud-test.conllu

If you can update that, especially the missing training data, I can rebuild the models and add those scores to the webpage.

Also, since the dataset is named `ang_oedt` in your git repo, do you want me using that name for the models?

**Comment by dmetola** [comment]
Hi,

Thanks for your response, and for spotting these issues.

> these files have some weird indenting:

I have sorted the indenting issues. Originally, the texts were annotated with those indents, and when training locally, the scripts removed them and moved everything to the left margin. In any case, I have removed them just to be sure everything works.

> this file is empty: 

I have also re-populated the train file, I don't know why, when renaming it in github, the content was removed. I hope it works now. If not, please let me know.

> Also, since the dataset is named ang_oedt in your git repo, do you want me using that name for the models?

No need to rename the models, the name is good as it is right now.

Can't wait to see the scores on the webpage. Thanks for everything!

**Comment by AngledLuffa** [comment]
A couple more minor issues:

What did you do with the lemmatizer?  It seems there are a bunch of
additional annotations in the lemma column, and our lemmatizer is not very
good at predicting those.  Did you drop them for the lemmatizer?

Line 16561 of the training set has a repeat in the ID column.  If you edit
it (hopefully yes), the IDs of the heads for the relations will also need
updating

```
# sent_id = LAWSWI1.004.001.
# text = Æltheodige mæn, gif hio hiora hæmed rihtan nyllað, of lande mid
hiora æhtum and mid synnum gewiten;
# text_en = Foreigners, if they will not regularise their unions, shall
depart from the land with their possessions and with their sins.
1       Æltheodige      elðēodig        ADJ     adjective
Case=Nom|Gender=Masc|Number=Plur        2       amod    _       _
2       mæn     mann    NOUN    common noun
Case=Nom|Gender=Masc|Number=Plur        19      nsubj   _
SpaceAfter=No
3       ,       ,       PUNCT   punctuation     Uninflected=Yes 8
punct   _       _
4       gif     gif (CONJ)      SCONJ   subordinating conjunction
Uninflected=Yes 8       mark    _       _
5       hio     hīe (PRON)      PRON    pronoun
Case=Nom|Number=Plur|Person=3|PronType=Prs      8       nsubj   _       _
6       hiora   hira (POSS)     PRON    pronoun
Case=Acc|Number=Sing|Person=3|Poss=Yes|PronType=Prs     7       det:poss
     _       _
7       hæmed   hǣmed   NOUN    common noun
Case=Acc|Gender=Neut|Number=Sing        8       obj     _       _
8       rihtan  rihtan(ge)      VERB    main verb
Uninflected=Yes|VerbForm=Inf    19      advcl   _       _
9       ne      ne      PART    particle
 Polarity=Neg|Uninflected=Yes    10      advmod  _       SpaceAfter=No
10      wyllað  willan  AUX     auxiliary verb
 Mood=Ind|Number=Plur|Tense=Pres|VerbForm=Fin    8       aux     _
SpaceAfter=No
10      ,       ,       PUNCT   punctuation     Uninflected=Yes 8
punct   _       _          <<<<----------------------
11      of      of ‘of, from, out of’ (PREP)    ADP     adposition
 Uninflected=Yes 12      case    _       _
12      lande   land    NOUN    common noun
Case=Dat|Gender=Neut|Number=Sing        19      obl:lmod        _       _
13      mid     mid ‘with’ (PREP)       ADP     adposition
 Uninflected=Yes 15      case    _       _
14      hiora   hira (POSS)     PRON    pronoun
Case=Dat|Number=Plur|Person=3|Poss=Yes|PronType=Prs     15      det:poss
     _       _
15      æhtum   ǣht     NOUN    common noun
Case=Dat|Gender=Fem|Number=Plur 19      obl     _       _
16      and     and 'and' (CONJ)        CCONJ   coordinating conjunction
     Uninflected=Yes 18      cc      _       _
17      mid     mid ‘with’ (PREP)       ADP     adposition
 Uninflected=Yes 18      case    _       _
18      synnum  synn    NOUN    common noun
Case=Dat|Gender=Fem|Number=Plur 15      conj    _       _
19      gewiten witan(ge)       VERB    main verb
Mood=Sub|Number=Plur|Tense=Pres|VerbForm=Fin    0       root    _
SpaceAfter=No
20      ;       ;       PUNCT   punctuation     Uninflected=Yes 19
 punct   _       _
```

**Comment by dmetola** [comment]
> What did you do with the lemmatizer?

That was a decision that was made during annotation. I already raised that issue with the annotators, saying that it may confuse the model. The reasoning was that, due to the nature of the language, those extra annotations for the lemma helped identify words that share lemma but are different at other linguistic levels. We are aware of the limitations, but we are hopeful that with extra annotated data the model will be able to disambiguate those cases.

> Line 16561 of the training set has a repeat in the ID column. 

Done, and relations updated

**Comment by AngledLuffa** [comment]
>  those extra annotations for the lemma helped identify words that share lemma but are different at other linguistic levels

... morphological features?

but it was just the case that the lemmatizer score is pretty low, and I was wondering if you'd experienced the same or if you'd done something to make it a bit more reliable, like dropping those extra annotations

Cycle in one of the dependency trees, words 16 & 17:

```
# sent_id = ÆHOM1.005.006.001
# text = Hwæt ða Herodes cyning ðis gehyrende wearð micclum astyred, and eal seo burhwaru samod mid him.
# text_en = Now king Herod hearing this was greatly troubled, and all the citizens together with him.
1       Hwæt    hwæt (INT)      INTJ    interjection    Uninflected=Yes 7       discourse       _       _
2       ða      ðā ‘then’       ADV     adverb  Uninflected=Yes 7       advmod  _       _
3       Herodes Herodes PROPN   proper noun     Case=Nom|Number=Sing    7       nsubj   _       _
4       cyning  cyning  NOUN    common noun     Case=Nom|Gender=Masc|Number=Sing        3       aposs   _       _
5       ðis     ðes-ðēos-ðis    PRON    pronoun Case=Acc|Gender=Neut|Number=Sing|PronType=Dem   6       obj     _       _
6       gehyrende       hīeran(ge)      VERB    main-verb       Tense=Pres|Uninflected=Yes|VerbForm=Part        7       advl    _       _
7       wearð   weorðan(ge)     VERB    main-verb       Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin   0       root    _       _
8       micclum miclum  ADV     adverb  Uninflected=Yes 9       advmod  _       _
9       astyred āstyrian        VERB    main-verb       Tense=Past|Uninflected=Yes|VerbForm=Part        7       xcomp   _       SpaceAfter=No
10      ,       ,       PUNCT   punctuation     Uninflected=Yes 14      punct   _       _
11      and     and 'and'       CCONJ   CCONJ   Uninflected=Yes 14      cc      _       _
12      eal     eall ‘all, every, entire’       DET     determiner      Case=Nom|Gender=Fem|Number=Sing 14      det     _       _
13      seo     se-sēo-ðæt      DET     demonstrative-article   Case=Nom|Gender=Fem|Number=Sing|PronType=DemArt 14      det     _       _
14      burhwaru        burhwaru        NOUN    common noun     Case=Nom|Gender=Fem|Number=Sing 7       nsubj   _       _
15      samod   samod ‘simultaneously’  ADV     adverb  Uninflected=Yes 9       advmod  _       _
16      mid     mid ‘with’      ADP     adposition      Uninflected=Yes 17      case    _       _
17      him     he      PRON    pronoun Case=Dat|Gender=Masc|Number=Sing|Person=3|PronType=Prs  16      obl     _       SpaceAfter=No
18      .       .       PUNCT   punctuation     Uninflected=Yes 7       punct   _       _
```

**Comment by dmetola** [comment]
Yeah, I noticed that in the lemmatizer when training locally.

I'll revise the dataset and come back to you later today. There shouldn't be any cycles or errors in it. Apologies for this

**Comment by dmetola** [comment]
I have corrected that dependency cycle, and run the models with the datasets a couple of times locally to make sure that there aren't any further issues. It should be OK now

About the performance of the lemmatizer, at this stage I think I'll keep the information in the dataset as is now. I'll discuss it with the people in charge of annotations, and run experiments locally to see if removing the extra information improves performance in future rounds of fine-tuning that I'll run with new data.

Thanks!

**Comment by AngledLuffa** [comment]
Here are the scores I got for individual annotators.  Does any of it look different from your expectations?

```
tokenize:
ang_oedt
   Tokens Sentences     Words
    99.93     71.13     99.93

pos:
ang_oedt
   UPOS    XPOS  UFeats AllTags
  93.52   81.94   86.20   72.40

lemma:
Lemma score:
ang_oedt 64.96

depparse:
Old_English-OEDT
  UAS   LAS  CLAS  MLAS  BLEX
83.63 77.84 73.12 69.96 73.12
```

**Comment by dmetola** [comment]
All looks the same to what I got locally.
When can I expect to get the results uploaded?
Thanks for this!

**Comment by AngledLuffa** [comment]
I think it should be visible now

**Comment by dmetola** [comment]
I still can't see it. I'm guessing the website still has to update or something.

**Comment by AngledLuffa** [comment]
https://stanfordnlp.github.io/stanza/available_models.html#old-english

**Comment by dmetola** [comment]
That's great, I can see it now. Thanks!

**Comment by AngledLuffa** [comment]
Been a while since we touched base on this.

I was looking through the word vectors, and I was wondering - are the only numbers in the word vectors in the form of Roman numerals?  If there is raw text in Arabic numberals such as 37, would you suggest converting that to xxxvii and looking that up in the 

Also, there seem to be no capitals, is that correct?

**Comment by dmetola** [comment]
Hi, thanks for your input, and apologies for not getting back to you sooner. 

As far as I am concerned, there are no Arabic numbers.

Regarding the presence of capitals, I think that when preparing the word vectors, there was some normalisation. Given the syntactic nature of the language, that does not make much of a difference, since the syntactic function of words is pretty much based on position in the sentence, and their morphological inflection. 

For your information, I am not involved in this project anymore, due to incompatibilities with my current role. I have transferred this project to Prof. Javier Martin Arista, whose email is javier.martin@unirioja.es
Going forward, if you have any questions about this project, he is your person of contact. 

Thank you very much for your help during this project. I really appreciate it, you have allowed me to fulfil a project that has been some years in the making.

**Comment by AngledLuffa** [comment]
I'm glad it was helpful!

In terms of having done normalization, it would be better if we replicated that normalization when using the word vectors.  Although if the details of how it was done are lost, I suppose that's just something we won't be able to do.

"Due to incompatibilities with my current role" is a great phrase.  I may find myself using that shortly...
