### ISSUE TITLE
How can I call run_tokenizer.py and other python training processors with toy data?

### ISSUE THREAD

**Issue by alicerogier555** [stanfordnlp/stanza-train#5]
Hello,

I tried to follow this Training Tutorials step by step. 
At the "Training and Evaluating Processors" section I realised that all the bash scripts located in the scripts dir  were replaced by python scripts located in the utils/training/ dir.
I called run_tokenizer.py with same arguments as the bash script, but it didn't work :

```
python3 stanza/utils/training/run_tokenizer.py UD_English-TEST --step 500
2021-03-17 11:33:39 INFO: Training program called with:
stanza/utils/training/run_tokenizer.py UD_English-TEST --step 500
2021-03-17 11:33:39 DEBUG: UD_English-TEST: en_test
2021-03-17 11:33:39 INFO: UD_English-TEST: saved_models/tokenize/en_test_tokenizer.pt does not exist, training new model
Traceback (most recent call last):
  File "stanza/utils/training/run_tokenizer.py", line 104, in <module>
    main()
  File "stanza/utils/training/run_tokenizer.py", line 101, in main
    common.main(run_treebank, "tokenize", "tokenizer")
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/stanza/utils/training/common.py", line 86, in main
    temp_output_file.name, command_args, extra_args)
  File "stanza/utils/training/run_tokenizer.py", line 68, in run_treebank
    seqlen = str(math.ceil(avg_sent_len(label_file) * 3 / 100) * 100)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/stanza/utils/avg_sent_len.py", line 11, in avg_sent_len
    with open(toklabels, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/tokenize/en_test-ud-train.toklabels'
```

What am I doing wrong ? How should I call these python functions with toy data ?

**Comment by AngledLuffa** [comment]
Sorry, I was being lazy and have not yet updated that part of the
documentation.  It is a two step process

1) build the training data

stanza/utils/datasets/prepare_tokenizer_treebank.py

2) run the training script

stanza/utils/training/run_tokenizer.py

**Comment by AngledLuffa** [comment]
I updated the docs as well.

**Comment by alicerogier555** [comment]
Thank you !
